spring:
  application:
    name: Config-Default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sujarani-Jena/Microservice-config
          clone-on-start: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

    instance:
      prefer-ip-address: true


